#!/bin/sh

## This script expects a csv file set in variable ADD
## (by default ~/.config/mailman/addresses.check)
## with five columns separated by ; without quotes
## Family name;First name;main@email.address;sometext;other@email.address
## It will send an email according to template "$1"

if [ -z "$ADD" ]; then
    ADD=$HOME/.config/mailman/addresses.check
fi

if [ ! -f "$ADD" ]; then
    grep "$0" ^##|sed -e 's/^## //g'
    exit 0
fi

if [ -z "$1" ]; then
    TEMPLATE="template.txt"
else
    TEMPLATE="$1"
fi

if [ ! -f "$TEMPLATE" ]; then
    echo "$TEMPLATE n'est pas un fichier source"
    exit 2
fi

echo "J'envoie le message de type $TEMPLATE"

if [ -n "$TEMPLATE" ]; then
    SUBJECT=$(grep ^Subject: "$TEMPLATE"|cut -f2 -d:)
    if [ -z "$SUBJECT" ]; then
        echo "Il n'y a pas de sujet"
        exit 2
    fi
    XFROM=$(grep ^From: "$TEMPLATE"|cut -f2 -d:)
    REALNAME=$(echo "$XFROM"|cut -f1 -d'<'|sed -e 's/ *$//g')
    ADDRESS=$(echo "$XFROM"|cut -f2 -d'<'|cut -f1 -d'>')
fi

DONE=0
WAIT=0

mkdir -p emails

while IFS="" read line 0<&3 ; do
    NOM=$(echo "$line"|cut -f1 -d';')
    PRENOM=$(echo "$line"|cut -f2 -d';')
    EMAIL=$(echo "$line"|cut -f3 -d';')
    if [ -n "$EMAIL" ]; then
        PWDP=$(pwd|sed -e 's|/|\\/|g')
        sed -e "s/__ID__/${EMAIL}/g;s/__FROM__/${ADDRESS}/g;s/__NAME__/${REALNAME}/g;s/__PWD__/${PWDP}/g" < muttrc > muttrc.now
        if [ ! -f emails/${EMAIL} ]; then
            touch emails/${EMAIL}
        fi
        if [ -n "$TEMPLATE" ]; then
            if grep -q "^X-Template: $TEMPLATE" emails/${EMAIL}; then
		DONE=$((DONE+1))
            else
                sed -e "/^Subject:/ d;/^From:/ d;s/__NOM__/${NOM}/g;s/__PRENOM__/${PRENOM}/g;s/__EMAIL__/${EMAIL}/g" < "$TEMPLATE" > message.txt
		if [ "$WAIT" -gt 0 ]; then sleep $((WAIT)); fi
                echo "J'envoie un mail à $PRENOM $NOM par l'adresse $EMAIL"
                mutt -F muttrc.now -e "my_hdr X-Template:$TEMPLATE" -s "$SUBJECT" "${EMAIL}" < "message.txt"
		WAIT=$((WAIT+5))
            fi
        fi
    fi
done 3< "$ADD"

if [ "$DONE" -gt 0 ]; then
	echo "$DONE courriers déjà envoyés"
fi
